<Project Sdk="Microsoft.NET.Sdk">

  <!-- Слой инфраструктуры: Entity Framework Core, PostgreSQL, реализация репозиториев -->
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderManagement.Application\OrderManagement.Application.csproj" />
  </ItemGroup>

</Project>
