<Project Sdk="Microsoft.NET.Sdk">

  <!-- Слой приложения: сценарии использования (CQRS), валидация, конвейерные behaviors -->
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Mediator.SourceGenerator">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderManagement.Domain\OrderManagement.Domain.csproj" />
  </ItemGroup>

</Project>
